name: aoc
description: Advent of Code 2022
version: 1.0.0
email: mark@mooiboek.nl

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  equatable: ^2.0.5
  file: ^6.1.4
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


